Update

diff --git a/.local/bin/k b/.local/bin/k
--- a/.local/bin/k
+++ b/.local/bin/k
@@ -1,5 +1,8 @@
 #!/usr/bin/env bash
 
-command -v kubectl >/dev/null 2>&1 || { echo >&2 "Cannot find kubectl in your PATH"; exit 1; }
+command -v kubectl >/dev/null 2>&1 || {
+    echo >&2 "Cannot find kubectl in your PATH"
+    exit 1
+}
 
 kubectl "$@"
diff --git a/.local/bin/wttr b/.local/bin/wttr
--- a/.local/bin/wttr
+++ b/.local/bin/wttr
@@ -1,5 +1,8 @@
 #!/usr/bin/env bash
 
-command -v curl >/dev/null 2>&1 || { echo >&2 "Cannot find curl in your PATH."; exit 1; }
+command -v curl >/dev/null 2>&1 || {
+    echo >&2 "Cannot find curl in your PATH."
+    exit 1
+}
 
 curl -4 "wttr.in/$@"
